{% set name = "jaxsim" %}
{% set version = "0.8.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaxsim-{{ version }}.tar.gz
  sha256: ce55b1ed3aae773fb853f95e215195a8fe90b0270437b7da53de57f03df2d99a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    # From build-system.requires:
    - wheel
    - setuptools >=64
    - setuptools-scm >=8
  run:
    # Main dependencies:
    - python >={{ python_min }}
    - coloredlogs
    - icub-models
    - jax >=0.4.26
    - jaxlib >=0.4.26
    - jaxlie >=1.3.0
    - jax-dataclasses >=1.4.0
    - optax >=0.2.3
    - pptree
    - qpax
    - rod >=0.3.3
    - trimesh
    - typing_extensions
    # Extra [viz] dependencies:
    - lxml
    - mediapy
    - mujoco >=3.0.0
    - scipy

test:
  imports:
    - jaxsim
  commands:
    - pip check
    - test "$(pip list | grep jaxsim | awk '{print $2}')" == "$PKG_VERSION"
    - pytest -vv tests/test_simulations.py
  source_files:
    - tests/*
  requires:
    - python {{ python_min }}
    - git
    - pip
    # Extra [testing] dependencies:
    - idyntree >=12.4
    - pytest >=6.0
    - pytest-benchmark
    - pytest-icdiff
    - robot_descriptions

about:
  home: https://github.com/ami-iit/jaxsim
  summary: A differentiable physics engine and multibody dynamics library for control and robot learning.
  dev_url: https://github.com/ami-iit/jaxsim
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xela-95
    - flferretti
    - diegoferigo
    - traversaro
