{% set name = "jaxsim" %}
{% set version = "0.8.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaxsim-{{ version }}.tar.gz
  sha256: 03082ac9116c90c46159339e0c2a2e1e6714114416dd23fb6e5b3458d5a0750a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    # From build-system.requires:
    - wheel
    - setuptools >=64
    - setuptools-scm >=8
  run:
    # Main dependencies:
    - jax_dataclasses >=1.4.0
    - python >={{ python_min }}
    - coloredlogs
    - icub-models
    - jax >=0.4.34
    - jaxlib >=0.4.34
    - jaxlie >=1.3.0
    - jax-dataclasses >=1.4.0
    - optax >=0.2.3
    - pptree
    - qpax
    - rod >=0.4.1
    - trimesh
    - typing_extensions
    # Extra [viz] dependencies:
    - lxml
    - mediapy
    - mujoco >=3.0.0
    - scipy

test:
  imports:
    - jaxsim
  commands:
    - pip check
    - test "$(pip list | grep jaxsim | awk '{print $2}')" == "$PKG_VERSION"
    - pytest -vv tests/test_simulations.py -k "not cartpole"
  source_files:
    - tests/*
  requires:
    - python {{ python_min }}
    - git
    - pip
    # Extra [testing] dependencies:
    - idyntree >=12.4
    - pytest >=6.0
    - pytest-benchmark
    - pytest-icdiff
    - robot_descriptions

about:
  home: https://github.com/ami-iit/jaxsim
  summary: A differentiable physics engine and multibody dynamics library for control and robot learning.
  dev_url: https://github.com/ami-iit/jaxsim
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xela-95
    - flferretti
    - diegoferigo
    - traversaro
